name = "parse-shenzjd-worker"
main = "src/worker.js"
compatibility_date = "2025-08-14"
workers_dev = true

# 如需绑定自定义路由，请改为：
# routes = [
#   { pattern = "example.com/*", zone_id = "YOUR_ZONE_ID" }
# ]


