name = "parse-shenzjd-com"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2025-08-14"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm dlx @cloudflare/next-on-pages@1"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"


